### ISSUE TITLE
Peer-to-peer code review [2021/07/29]

### ISSUE THREAD

**Issue by fernandorpm** [EroAuditore/leaderboard#3]
# Peer-to-peer code review [2021/07/29]

## Leave all of your comments and suggestions below!

**Comment by gabrielyea** [comment]
Good work
![](https://media2.giphy.com/media/uGPprkG8KQny9Ei5qD/giphy.gif)

**Comment by ArthurGC** [comment]
Great job!!
![gif](https://media2.giphy.com/media/MXvdnDyiaLKQShtvTr/giphy.gif?cid=ecf05e475f567r0xmzqvp0txpnrnqb70tt1havmmeocug9gy&rid=giphy.gif&ct=g)
